<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Jayashree" name="com.testng_Test.Test_ng_Iretry" tests="7" failures="0" timestamp="2022-11-22T06:40:30 IST" time="3.063" errors="1">
  <testcase name="salary" time="1.017" classname="com.testng_Test.Test_ng_Iretry">
    <skipped/>
  </testcase> <!-- salary -->
  <system-out/>
  <testcase name="id" time="0.001" classname="com.testng_Test.Test_ng_Iretry"/>
  <system-out/>
  <testcase name="dob" time="0.002" classname="com.testng_Test.Test_ng_Iretry"/>
  <system-out/>
  <testcase name="salary" time="1.016" classname="com.testng_Test.Test_ng_Iretry">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.testng_Test.Test_ng_Iretry.salary() didn&#039;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.testng_Test.Test_ng_Iretry.salary() didn't finish within the time-out 1000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- salary -->
  <system-out/>
  <testcase name="salary" time="1.014" classname="com.testng_Test.Test_ng_Iretry">
    <skipped/>
  </testcase> <!-- salary -->
  <system-out/>
  <testcase name="company" time="0.011" classname="com.testng_Test.Test_ng_Iretry"/>
  <system-out/>
  <testcase name="emp" time="0.002" classname="com.testng_Test.Test_ng_Iretry"/>
  <system-out/>
</testsuite> <!-- com.testng_Test.Test_ng_Iretry -->
